name: Changeset PR & Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run Tests
        run: yarn workspace auto-hyphen-utils test

      - name: Run Lint
        run: yarn lint

      - name: Build Package
        run: yarn workspace auto-hyphen-utils build

  create-changeset-pr:
    name: Create Changeset PR
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Create Changesets Pull Request
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'ci(changesets): version packages'
          version: yarn changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-npm:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: create-changeset-pr
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Publish to NPM
        run: yarn changeset:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send Slack Notification
        if: success()
        run: echo "Successfully published to NPM"