name: NPM Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn Berry
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create and configure .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Package
        run: yarn workspace auto-hyphen-utils run build

      - name: Create Changesets Version
        run: |
          yarn changeset version
          git add .
          git diff --staged --quiet || git commit -m "chore: version packages"

      - name: Publish to NPM
        run: yarn changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}