name: NPM Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn Berry
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create and configure .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Changeset Version and PR
        uses: changesets/action@v1
        with:
          commit: "chore: version packages"
          title: "chore: version packages"
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: version

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn Berry
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create and configure .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: yarn changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}