name: Changeset PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Check Installed Modules
        run: ls -la .yarn node_modules || true

      - name: Run Tests
        run: yarn workspace auto-hyphen-utils test

      - name: Run Lint
        run: yarn lint

      - name: Build Package
        run: yarn workspace auto-hyphen-utils build